name: Update Repository Properties

on:
workflow_call:

jobs:
update-properties:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v2

# Get repository language dynamically
- name: Get repository language
run: |
language=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
https://github.prodlib.travp.net/api/v3/repos/${{ github.repository }}/languages | jq -r 'keys | join(",")')

if [[ -z "$language" ]]; then
language="unknown"
fi

echo "language=$language" >> $GITHUB_ENV
echo "Detected Language: $language"

# Check if config file exists
- name: Check if file exists
run: |
FILE_PATH=".github/config.yaml"
if [[ -f "$FILE_PATH" ]]; then
echo "file_exists=true" >> $GITHUB_ENV
else
echo "file_exists=false" >> $GITHUB_ENV
fi

# Extract multiple parameters dynamically + Add language property
- name: Get multiple parameter values
run: |
PARAMS=("run_test" "code_quality_analysis" "security_scan" "performance_test") # Add more parameters as needed
PARAMS_JSON="[{\"property_name\":\"technology\",\"value\":\"${{ env.language }}\"}]," # Include language first

if [[ "${{ env.file_exists }}" == "true" ]]; then
for param in "${PARAMS[@]}"; do
value=$(grep "$param" ".github/config.yaml" | sed -E 's/.*[:=] *//')
if [[ -z "$value" ]]; then
value="not_found"
fi
echo "$param=$value" >> $GITHUB_ENV
PARAMS_JSON+="{\"property_name\":\"$param\",\"value\":\"$value\"},"
echo "Extracted: $param=$value"
done
else
for param in "${PARAMS[@]}"; do
echo "$param=not_found" >> $GITHUB_ENV
PARAMS_JSON+="{\"property_name\":\"$param\",\"value\":\"not_found\"},"
echo "Default: $param=not_found"
done
fi

# Remove last comma for valid JSON format
PARAMS_JSON="[${PARAMS_JSON%,}]"
echo "params_json=$PARAMS_JSON" >> $GITHUB_ENV

# Update repository properties dynamically
- name: Update repository properties
run: |
curl -X PATCH -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
-H "Accept: application/vnd.github.mercy-preview+json" \
-H "Content-Type: application/json" \
https://github.prodlib.travp.net/api/v3/repos/${{ github.repository }}/properties/values \
-d "{\"properties\": ${{ env.params_json }}}"
